# Generated by Django 3.1.6 on 2023-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstuser',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('fnm', models.CharField(max_length=40)),
                ('mno', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=40)),
                ('pwd', models.CharField(max_length=13)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
    ]
