# Generated by Django 3.1.6 on 2023-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batchid', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=25)),
                ('startdate', models.DateField()),
                ('batchtime', models.CharField(max_length=25)),
                ('facultyname', models.CharField(max_length=25)),
            ],
        ),
    ]
